### PR TITLE
Fix livechat bridge

### PR DESCRIPTION
**Pull request by d-gubert**
# What? :boat:

Fix wrong permission validation for livechat bridge
# Why? :thinking:

It's a fix. It's self explanatory
# Links :earth_americas:

# PS :eyes:

### CODE REVIEW

**Comment by cuonghuunguyen** [comment]
Hi, could u cover the the bug in h#430 also pls?

**Comment by d-gubert** [comment]
Hey @cuonghuunguyen ! This fix covers exactly that bug :)

**Comment by cuonghuunguyen** [comment]
Thank you very much!

**Comment by felipetomm** [comment]
Hi @d-gubert !
I think that issue persist partially. We have Apps runing in RocketChat 3.16.1 and 3.15.3 **enterprise**. 
For example, an specific method **getLivechatDepartmentByIdOrName**, used for Omnichannel Apps, like Whatsapp and Telegram, run normally in the server on version 3.15.3, but in 3.16.1, the result from this method is **undefined**.

Please, can you review this?

**Comment by cuonghuunguyen** [comment]
Thats because while refactoring, they didnt add all permissions into defaultPermission

**Comment by felipetomm** [comment]
Hmm, but i think the permission of that method is livechat-department, right?
Has any way to adjust this without an RC release? I try add this in my App.json, but has no success:
```json
...
"implements": [
        "IPostLivechatRoomStarted"
    ],
    "permissions": [
        {
            "name": "livechat-department.read"
        }
    ]
}
```

**Comment by felipetomm** [comment]
Ok.. with server logs, i find the correct permission: **livechat-department.multiple**, and that's ok for my App.
But, with external Apps, the solution is an Apps-Engine fix?

**Comment by d-gubert** [comment]
@felipetomm the `livechat-department.multiple` permission is only required for grabbing multiple departments with the `getDepartmentsEnabledWithAgents` method, other methods should work with ´livechat-department.read` as well.

@cuonghuunguyen the list of default permissions hasn't changed with the refactoring. But new permissions introduced _after_ the permission system was implemented will not be part of this permission set. Currently, we have 2 permissions that are not default, IIRC: `cloud.workspace-token` and `livechat-department.multiple`

**Comment by felipetomm** [comment]
Thanks @d-gubert !

**Comment by cuonghuunguyen** [comment]
@d-gubert do u think that adding all of them into some kind of `Dictionary` or `enum` and get them from there. Default permissions will take all values from there.
By that way u could save some lines of code and also avoid missing default permissions

**Comment by murtaza98** [comment]
> Hi @d-gubert !
> I think that issue persist partially. We have Apps runing in RocketChat 3.16.1 and 3.15.3 **enterprise**.
> For example, an specific method **getLivechatDepartmentByIdOrName**, used for Omnichannel Apps, like Whatsapp and Telegram, run normally in the server on version 3.15.3, but in 3.16.1, the result from this method is **undefined**.
> 
> Please, can you review this?

Hey guys, this should be fixed with this PR PR: https://github.com/RocketChat/Rocket.Chat/pull/22587
It's currently under review and if all goes well, it will be release with the next core release

**Pull request merged**
