### PR TITLE
[NEW] Add Multi-Select setting interfaces on Apps

### PR DESCRIPTION
**Pull request by murtaza98**
# What? :boat:

Added new interfaces for multi-select settings within app

# Why? :thinking:

# Links :earth_americas:

# PS :eyes:

### CODE REVIEW

**Comment by murtaza98** [comment]
Hi Team @RocketChat/apps, Could you please review this PR?

**Comment by graywolf336** [comment]
Is there a corresponding Rocket.Chat PR for this or is this already supported by Rocket.Chat? If so, what does it look like on the Apps configuration/settings screen?

**Comment by murtaza98** [comment]
No PR for Core is needed, its just a matter of defining these typescript interfaces to support this.

Here's how it looks in action
image

**Comment by graywolf336** [comment]
Are the values provided like a regular select?

**Review by graywolf336 — APPROVED** [review]

**Pull request merged**
