### PR TITLE
Discussion create

### PR DESCRIPTION
**Pull request by marceloschmidt**
# What? :boat:

- Added discussionRoom and type to messages, and added parentRoom to room;

# Why? :thinking:
This will allow us to create discussions via apps.

### CODE REVIEW

**Comment by d-gubert** [comment]
The current implementation allows a discussion to be created _without_ a parent/origin message in the parent room. Is this something we'd like to allow? @marceloschmidt @ggazzo @sampaiodiego

**Comment by marceloschmidt** [comment]
Now that you mentioned, it doesn't seem to make much sense.

**Comment by marceloschmidt** [comment]
Though, do we have this type of logic here?

**Comment by d-gubert** [comment]
@marceloschmidt The API as it is allows that to happen as much as the implementation on the Rocket.Chat side, so if we want to change something, we're gonna have to change in both places 😛 

I think the best thing we could do here for the developer is to provide a `createDiscussion(discussion: IRoom, origin: IMessage)` method, which would create the discussion AND the origin/parent message if needed. 

The only problem is... where do we put it? In the `IModify` interface? 🤔

**Comment by sampaiodiego** [comment]
on Rocket.Chat side we have a [createDiscussion](https://github.com/RocketChat/Rocket.Chat/blob/develop/app/discussion/server/methods/createDiscussion.js#L124) method that handles everything, you can provide either a `roomId` or a `messageId`..

> I think the best thing we could do here for the developer is to provide a createDiscussion(discussion: IRoom, origin: IMessage) method, which would create the discussion AND the origin/parent message if needed.

an API like this makes more sense to me :+1:

**Comment by d-gubert** [comment]
Oooh, I've recently come to realize that a message is _always_ created along with a discussion, even if the user clicks on the `Start a discussion` message action 😬 So if we were to create a bridge method that calls the `createDiscussion` method on the Rocket.Chat side, it looks like a perfect solution then?

I might be able to give this a try today

**Comment by marceloschmidt** [comment]
@d-gubert did you manage to do it?

**Comment by marceloschmidt** [comment]
I'm closing this one in favor of a different branch with the proposed approach.

**Pull request closed without merging**
