### PR TITLE
added support for all built-in node modules

### PR DESCRIPTION
**Pull request by murtaza98**
# What? :boat:

added support for all built-in node modules

# Why? :thinking:

Fixes Issue --> #204 
# Links :earth_americas:

Built-in module reference --> https://github.com/nodejs/node/tree/master/lib

# PS :eyes:

### CODE REVIEW

**Comment by murtaza98** [comment]
@lolimay @d-gubert Please Review :)

**Comment by lolimay** [comment]
Hi @murtaza98 ! Was this change by mistake https://github.com/RocketChat/Rocket.Chat.Apps-engine/pull/249/commits/b46f86c58e391e0fceb49c794adbb58ff20c02ad#diff-40cd679dee8a1f80b13930e70f0ddf50R129?

**Comment by murtaza98** [comment]
@lolimay, its a mistake. Did some changes after the PR. 

Btw, I'm closing this PR based on ur suggestion [here](https://github.com/RocketChat/Rocket.Chat.Apps-engine/issues/204#issuecomment-605053528)

**Comment by lolimay** [comment]
> However currently the app engine only support 4 built in modules as u can see in [this](https://github.com/RocketChat/Rocket.Chat.Apps-engine/blob/41aab31caa82b20ace7b8b354709f52d38d2bc73/src/server/misc/Utilities.ts) file. 
So what I am thinking, we can add some support for some more built in node modules which are **safe**. We won't include node modules like `vm`,  `process`, `child_process` which are a not safe from security stand point. However we can include modules like `assert`, `stream`, `timers`, etc, which are harmless.
> 
> What do u think abt this?
>  I u agree, then I will create a list of all safe modules n submit a pull request.

Hi, regarding your comment above. I will appreciated if you can help us add more *secure* node built-in modules into that file! Are you still passionate on it?

**Comment by murtaza98** [comment]
@lolimay , glad u liked this idea, will start to work on it.

**Pull request closed without merging**
